# 批量按顺序启动一批容器
# 定义要运行的服务
version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      # 这样 docker-compose 就会先启动另外两个，再启动这个,解决顺序问题。
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - C:\Users\CL2021\Desktop\mysql2:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - C:\Users\CL2021\Desktop\redis:/data

# 桥接网络
# version: '3.8'
# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - '3000:3000'
#     networks:
#       - common-network
#   mysql-container:
#     image: mysql
#     volumes:
#       - /Users/guang/mysql-data:/var/lib/mysql
#     networks:
#       - common-network
#   redis-container:
#     image: redis
#     volumes:
#       - /Users/guang/aaa:/data
#     networks:
#       - common-network
# networks:
#   common-network:
#     driver: bridge
